### ISSUE TITLE
How to set selected items

### ISSUE THREAD

**Issue by kingskull619** [djsmithme/Multi-Column-Select#6]
Hi im trying to do a edit form, when some values are selected by default.
How can i put selected items, by default?

like:

```html
<div id="selectcontrolm">
	<select name="cassr" class="browser-default" multiple>
		<option value="Audi" selected>Audi22</option>
		<option value="Bugatti" selected>Bugatti</option>
		<option value="Chrysler">Chrysler</option>
		<option value="Daihatsu">Daihatsu</option>
    </select>
</div>
```

**Comment by djsmithme** [comment]
I need to add it as it currently clears the form when it scans for items.

**Comment by djsmithme** [comment]
Bit late but this has been added, it now works as you have outlined above.
