### ISSUE TITLE
Multiselect

### ISSUE THREAD

**Issue by Gypsyy** [djsmithme/Multi-Column-Select#7]
I found a minor bug.
If you're useing the multi select and you click on more than one option, I get the error: 
```javascript
args.push() is not a function
``` 
because the variable "selection" isn't an array. 
To fix this just add
around Line 115:
```javascript
                    args.push($select.val());
```
instead of
```javascript
                    args = $(select).val());
```
and Line 133:
```javascript
                args.push($select.val());
```

And thank you for the project.

**Comment by djsmithme** [comment]
Sorry for the delay in my reply. I have added the fix provided, thank you for taking time to highlight this. Happy Coding.
