### ISSUE TITLE
normal select is displayed above your multi-column select

### ISSUE THREAD

**Issue by schaferdave** [djsmithme/Multi-Column-Select#8]
Fun project, I'd like to use it but I can't crack the code with the multi select.    I have the same problem as your demo - a normal select is displayed above your cool select.   They seem to be two views on the same control.    

Tested on Chrome/Edge.

**Comment by djsmithme** [comment]
Not done anything to this repo for ages and with no tests could just be bugged but the demo is showing two forms each a single input. The first is a single selection with the original control hidden, the second is a multi selection with the original control shown. This can be changed in options (default hideselect : true) 
https://github.com/djsmithme/Multi-Column-Select/blob/master/demo.html#L110

The plugin just creates a new div layout  next to the original form control, it then manipulates the control. To be honest you don't need jquery for this anymore I'll look to update it.

**Comment by schaferdave** [comment]
Thank you djsmithme.    Hideselect:true fixes the issue.      I'll be watching for your updates.
